# Generated by Django 4.1.7 on 2023-03-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="engine",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="cars",
            name="type",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="cars",
            name="year",
            field=models.IntegerField(default="0"),
        ),
    ]
