# Generated by Django 4.1.7 on 2023-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0002_cars_engine_cars_type_cars_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="0", max_length=200)),
                (
                    "founding_year",
                    models.IntegerField(default="0", max_length=10, null=True),
                ),
                (
                    "owner_name",
                    models.CharField(default="0", max_length=200, null=True),
                ),
                ("rarity", models.CharField(default="0", max_length=200, null=True)),
                (
                    "hq_address",
                    models.CharField(default="0", max_length=200, null=True),
                ),
            ],
        ),
    ]
