# Generated by Django 4.1.7 on 2023-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0004_alter_cars_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="name",
            field=models.CharField(default="0", max_length=200),
        ),
    ]
