# Generated by Django 4.1.7 on 2023-03-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0006_alter_cars_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="founding_year",
            field=models.IntegerField(default="0", null=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(default="0", max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_of_birth", models.IntegerField(default="0")),
                ("address", models.CharField(default="0", max_length=500)),
                ("gender", models.CharField(default="0", max_length=100)),
                ("phone", models.IntegerField(default="0")),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django1.brand"
                    ),
                ),
            ],
        ),
    ]
