# Generated by Django 4.1.7 on 2023-03-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0008_alter_customers_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="django1.brand",
            ),
        ),
        migrations.CreateModel(
            name="CarOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_id",
                        to="django1.cars",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_id",
                        to="django1.customers",
                    ),
                ),
            ],
        ),
    ]
