# Generated by Django 4.1.7 on 2023-03-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0009_alter_cars_name_carownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="carownership",
            name="name_of_dealer",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="carownership",
            name="date",
            field=models.DateField(default="2000-10-10"),
        ),
    ]
